
version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: eventpass
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  replica:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: eventpass_replica
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - replica_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  replica_data:
