global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerting_rules.yml"

scrape_configs:
  # Backend API metrics
  - job_name: 'backend'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true

  # Frontend metrics (if Next.js exposes metrics)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 30s

  # Worker service metrics
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8081']
    scrape_interval: 15s

  # Reprinter service metrics
  - job_name: 'reprinter'
    static_configs:
      - targets: ['reprinter:8082']
    scrape_interval: 15s

  # PostgreSQL metrics (if pg_stat_statements is enabled)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # MinIO metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s
    metrics_path: '/minio/v2/metrics/cluster'

  # Node exporter for system metrics (if deployed)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
