// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CheckIn struct {
	ID          int32
	EventID     int32
	InviteeID   pgtype.Int4
	CheckedInAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Event struct {
	ID       int32
	Name     string
	Date     pgtype.Timestamp
	Location string
}

type Invitee struct {
	ID            int32
	EventID       int32
	Email         string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	QrCodeUrl     pgtype.Text
	HmacSignature pgtype.Text
	State         string
	GiftClaimedAt pgtype.Timestamp
	ExpiresAt     pgtype.Timestamptz
	Status        string
	DeletedAt     pgtype.Timestamptz
	AnonymizedAt  pgtype.Timestamptz
}

type Order struct {
	ID           int32
	UserID       pgtype.UUID
	EventID      int32
	Status       string
	ExpiresAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	AnonymizedAt pgtype.Timestamptz
}

type ReprintRequest struct {
	ID        int32
	InviteeID int32
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	AnonymizedAt pgtype.Timestamptz
}
