// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: reprint_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReprintRequest = `-- name: CreateReprintRequest :one
INSERT INTO reprint_requests (
  invitee_id,
  user_id
) VALUES (
  $1, $2
) RETURNING id, invitee_id, user_id, created_at
`

type CreateReprintRequestParams struct {
	InviteeID int32
	UserID    pgtype.UUID
}

func (q *Queries) CreateReprintRequest(ctx context.Context, arg CreateReprintRequestParams) (ReprintRequest, error) {
	row := q.db.QueryRow(ctx, createReprintRequest, arg.InviteeID, arg.UserID)
	var i ReprintRequest
	err := row.Scan(
		&i.ID,
		&i.InviteeID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
