name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: ./apps/backend/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/backend:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: ./apps/frontend/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/frontend:latest

    - name: Build and push worker image
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: ./apps/workers/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/worker:latest

    - name: Build and push reprinter image
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: ./apps/reprinter/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/reprinter:latest

  run-tests:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name of the test
      run: echo "No tests configured yet"
